-- Keymaps are automatically loaded on the VeryLazy event
-- Default ig/keymaps.lua
-- Add any additional keymaps here
-- Split terminal in a new window
-- This file is automatically loaded by lazyvim.config.init
